# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Duoscribe

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build-test-lint:
    runs-on: ubuntu-latest
    container:
      image: houallet/alpine-go:1.1.2
    steps:
      - uses: actions/checkout@v3
      - run: git config --global --add safe.directory /__w/duoscribe/duoscribe
      
      - name: Build
        run: make build
        
      - name: Unit Tests
        run: make utest
        
      - name: Lint
        run: make lint

  integration-tests:
    environment: MR
    runs-on: ubuntu-latest
    container:
      image: houallet/alpine-go:1.1.2
      env: 
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
    steps:
      - uses: actions/checkout@v3
      - run: git config --global --add safe.directory /__w/duoscribe/duoscribe
      - name: Integration Tests
        run: make build itest