# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build-test-lint:
    environment: MR
    runs-on: ubuntu-latest
    container:
      image: houallet/alpine-go:1.1.0
    steps:
      - uses: actions/checkout@v3
      - run: git config --global --add safe.directory /__w/duoscribe/duoscribe
    
      - name: Build
        run: make build

      - name: Unit Tests
        run: make utest
      
      - name: Integration Tests
        run: make itest
      
      - name: Lint
        run: make lint
